starter/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('tugas.urls')),
    path('story1/',include('story1.urls')),
    path('story5/', include('story5.urls')),
]

story1/urls.py
from django.urls import path
from .views import *

app_name = "story1"
urlpatterns = [
    path('',index,name='story1'),
]

story5/urls.py
from django.urls import path
from .views import *

app_name = "story5"
urlpatterns = [
    path('',jadwal,name='jadwal'),
    path('savejadwal', savejadwal),
    path('detail/<int:myid>',add_detail,name='detail'),
    path('delete/<int:myid>',delete_detail,name='delete_detail'),
]

tugas/urls.py
from django.urls import path
from .views import *

app_name = "tugas"
urlpatterns = [
    path('',home,name='home'),
    path('about/',about,name='about'),
    path('more/',more,name='more'),
]

story1/models.py
from django.db import models

# Create your models here.

story5/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime, date

# Create your models here.
class Jadwal(models.Model):
    mata_kuliah = models.CharField(max_length=200)
    dosen = models.CharField(max_length=200,default='none')
    jumlah_sks = models.CharField(max_length=200,default='none')
    deskripsi = models.CharField(max_length=200,default='none')
    semester = models.CharField(max_length=200,default='none')
    ruangan = models.CharField(max_length=200,default='none')

class Post(models.Model):
    author = models.ForeignKey(Jadwal, on_delete = models.CASCADE)
    content = models.CharField(max_length=125)
    published_date = models.DateTimeField(default=timezone.now)
    

tugas/models.py
from django.db import models

# Create your models here.

story5/forms.py
from django import forms
from .models import Jadwal

class detail_matkul(forms.ModelForm):
    class Meta:
        model = Jadwal
        fields = ['mata_kuliah', 'dosen', 'jumlah_sks', 'deskripsi', 'semester', 'ruangan']
    error_messages = {
        'required' : 'Please Type'
    }
    input_attrs1 = {
        'type' : 'text',
        'placeholder' : 'Nama mata kuliah',
        'style' : 'background-color: #E8EEF2'
    }
    input_attrs2 = {
        'type' : 'text',
        'placeholder' : 'Nama dosen',
        'style' : 'background-color: #E8EEF2'
    }
    input_attrs3 = {
        'type' : 'text',
        'placeholder' : 'Jumlah SKS',
        'style' : 'background-color: #E8EEF2'
    }
    input_attrs4 = {
        'type' : 'text',
        'placeholder' : 'Deskripsi mata kuliah',
        'style' : 'background-color: #E8EEF2'
    }
    input_attrs5 = {
        'type' : 'text',
        'placeholder' : 'Semester',
        'style' : 'background-color: #E8EEF2'
    }
    input_attrs6 = {
        'type' : 'text',
        'placeholder' : 'Nomor ruangan',
        'style' : 'background-color: #E8EEF2'
    }
    mata_kuliah = forms.CharField(label='Mata Kuliah', required=True, max_length=27, widget=forms.TextInput(attrs=input_attrs1))
    dosen = forms.CharField(label='Nama Dosen', required=True, max_length=27, widget=forms.TextInput(attrs=input_attrs2))
    jumlah_sks = forms.CharField(label='Jumlah SKS', required=True, max_length=27, widget=forms.TextInput(attrs=input_attrs3))
    deskripsi = forms.CharField(label='Deskripsi Mata Kuliah', required=True, max_length=27, widget=forms.Textarea(attrs=input_attrs4))
    semester = forms.CharField(label='Semester', required=True, max_length=27, widget=forms.TextInput(attrs=input_attrs5))
    ruangan = forms.CharField(label='Nomor Ruangan', required=True, max_length=27, widget=forms.TextInput(attrs=input_attrs6))

tugas/forms.py
from django import forms

##Create your forms here

story1/views.py
from django.shortcuts import render,redirect

# Create your views here.
def index(request):
    return render(request,'index.html', {})

story5/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import *
from .models import *

# Create your views here.
response = {}
def jadwal(request):
    form = detail_matkul()
    matkuls = Jadwal.objects.all()
    response['matkuls'] = matkuls
    response['form'] = form
    return render(request,'Jadwal.html', response)

def savejadwal(request):
    form = detail_matkul(request.POST or None)
    if (form.is_valid and request.method == 'POST'):
        response['mata_kuliah'] = request.POST['mata_kuliah']
        response['dosen'] = request.POST['dosen']
        response['jumlah_sks'] = request.POST['jumlah_sks']
        response['deskripsi'] = request.POST['deskripsi']
        response['semester'] = request.POST['semester']
        response['ruangan'] = request.POST['ruangan']
        matkul = Jadwal(mata_kuliah=response['mata_kuliah'], dosen=response['dosen'], jumlah_sks=response['jumlah_sks'], deskripsi=response['deskripsi'], semester=response['semester'], ruangan=response['ruangan'],)
        matkul.save()
        
        return HttpResponseRedirect('/story5')
    else:
        return HttpResponseRedirect('/')

def add_detail(request, myid):
    matkul = Jadwal.objects.get(id=myid)
    response['matkul'] = matkul
    return render(request,'mata_kuliah.html',response)

def delete_detail(request, myid):
    Jadwal.objects.get(id=myid).delete()
    return HttpResponseRedirect('/story5')

tugas/views.py
from django.shortcuts import render,redirect

# Create your views here.
def home(request):
    return render(request,'Home.html', {})
def about(request):
    return render(request,'About.html', {})
def more(request):
    return render(request,'More.html', {})

story1/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Story1</title>
    <style>
        table, th, td {
          border: 1px solid black;
          border-collapse: collapse;
        }
        th, td {
          padding: 5px;
          text-align: left;    
        }
        </style>
</head>
<body>
    <h1>Profil saya </h1>
    <table style="width:100%">
        <tr> 
            <th>Nama</th>
            <td>Gerrad Natanael Daloma</td>
        </tr>
        <tr> 
            <th>NPM</th>
            <td>1906398704</td>
        </tr>
        <tr> 
            <th>Angkatan</th>
            <td>2019</td>
        </tr>
        <tr> 
            <th>Hobi</th>
            <td>
                <p>
                    -Denger musik
                    -Main musik
                    -Main catur
                    -Baca webtoon, manhwa, manhua
                    -Ngoding
                    -Olahraga
                </p>
            </td>
        </tr>
        <tr> 
            <th>Deskripsi</th>
            <td>
                <p>Saya lahir di Jakarta pada tanggal 11 Juni 2001. Saat ini saya tengah mengenyam pendidikan
                    di Universitas Indonesia, pada jurusan Ilmu Komputer.Sejak kecil saya begitu tertarik dengan
                    hal-hal yang mengandung matematika serta logika. Sebelumnya, saya sempat berpikir untuk berkuliah
                    di jurusan matematika, namun entah kenapa ketertarikan saya lebih besar kepada Ilmu Komputer.
                    Saya begitu suka mendengar serta memainkan alat musik, membaca komik, serta olahraga. Satu hal lagi
                    mengenai diri saya, yakni saya begitu menyukai warna hitam dan putih.
                </p>
            </td>
        </tr>
        <tr> 
            <th>Tempat Kuliah</th>
            <td>Universitas Indonesia</td>
        </tr>
        <tr> 
            <th>Foto</th>
            <td>2019</td>
        </tr>
        <tr> 
            <th>Riwayat Pendidikan</th>
            <td>
                <p>
                    -SDN 04 Cilandak Barat
                    -SMPN 85 Jakarta Selatan
                    -SMAN 34 Jakarta Selatan
                </p>
            </td>
        </tr>
        <tr> 
            <th>Media Sosial</th>
            <td>
                <p>
                    -Line = gerradnd
                    -IG = gerrad_nd
                </p>
            </td>
        </tr>
    </table>
<br>
<div>
<a href="{% url 'tugas:home' %}"><b>Story 4</b></a>
</div>
</body>
</html>

story5/templates/Jadwal.html
{% extends 'base.html' %}
{% load static %}
	{% block content %}
        <div class="card">
		</br>
		<h1 style='text-align: center; color: #0B3954'><b>Form untuk Mengisi Mata Kuliah</b></h1>
		</br>
	    <div class='row'>
		<div class='col-sm-6'>
	    	    <form action='savejadwal' method='POST'>
            		{% csrf_token %}
	    	        <table>
	    		{{ form.as_table }}
	    	        </table>
			</br>
	    		<input type='submit' value='Submit'>
            	    </form>
            	</div>
		<div class='col-sm-6'>
		    <table style="width:50%; border:1px solid black; background-color: #E8EEF2;">
			<tr>
			    <th style="border:1px solid black">List Mata Kuliah</th>
			    <th style="border:1px solid black">Hapus Mata Kuliah</th>
			</tr>
			{% for a in matkuls %}
			<tr>
	 	            <td style="border:1px solid black"><a href="{% url 'story5:detail' myid=a.id %}" style='color: black;'>{{ a.mata_kuliah }}</a></td>
	  	            <td style="border:1px solid black"><a href="{% url 'story5:delete_detail' myid=a.id %}" style='color: black'>Delete</a></td>
			</tr>
			{% endfor %}
		    </table>
	        </div>
		    
            </div>

        </div>
	{% endblock %}

story5/templates/mata_kuliah.html
{% extends 'base.html' %}
{% load static %}
	{% block content %}
        <div class="card">
	</br>
	<h1 style="text-align: center; color: #0B3954"><b>Detail Mata Kuliah {{ matkul.mata_kuliah }}</b></h1>
	</br>
	<table style='width: 40%; margin-left: auto; margin-right: auto; text-align: center; border:1px solid black; background-color: #E8EEF2;'>
	    <tr style="border:1px solid black;">
		<th style="border:1px solid black;"><h3> Mata Kuliah</h3></th>
		<td><h3>{{ matkul.mata_kuliah }}</h3></td>
	    </tr>
	    <tr style="border:1px solid black;">
		<th style="border:1px solid black;"><h3> Nama Dosen</h3></th>
		<td><h3>{{ matkul.dosen }}</h3></td>
	    </tr>
            <tr style="border:1px solid black;">
		<th style="border:1px solid black;"><h3> Jumlah SKS</h3></th>
		<td><h3>{{ matkul.jumlah_sks }}</h3></td>
	    </tr>
            <tr style="border:1px solid black;">
		<th style="border:1px solid black;"><h3> Deskripsi Mata Kuliah</h3></th>
		<td><h3>{{ matkul.deskripsi }}</h3></td>
	    </tr>
            <tr style="border:1px solid black;">
		<th style="border:1px solid black;"><h3> Semester</h3></th>
		<td><h3>{{ matkul.semester }}</h3></td>
	    </tr>
            <tr style="border:1px solid black;">
		<th style="border:1px solid black;"><h3> Mata Kuliah</h3></th>
		<td><h3>{{ matkul.ruangan }}</h3></td>
	    </tr>
	</table>
	</br>
        </div>
	{% endblock %}

tugas/templates/About.html
{% extends 'base.html' %}
{% load static %}

	{% block content %}
        <div class="card">
            <div class="row">
                <div class="col-sm-6">
                    <img class="card-imagea" src="{% static 'FR26.jpg' %}" style="border-radius: 10%;">
                </div>
                <div class="col-sm-6">
                    <h2 style="margin-top: 10%; font-size: 60px; color: rgb(75, 46, 1)"><b>About Me</b></h2>
                    <p style="font-size: 40px; color: rgb(75, 46, 1)">An energic and active College student from Univerisity of Indonesia, majoring in Computer Science, 
                        who's still learning programming with huge enthusiasm.
                    </p>
                </div>
            </div>
                <div class="row" style="background-color: #F3FFBD;">
                    <div class="col-sm-4">
                        <h2>SKILLS</h2>
                        <div class="row">
                            <div class="col-sm-6">
                                <img src="{% static 'python.png' %}" class="card-imagea">
                            </div>
                            <div class="col-sm-6">
                                <img src="{% static 'java.png' %}" class="card-imagea">
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-6">
                                <img src="{% static 'drum.png' %}" class="card-imagea">
                            </div>
                            <div class="col-sm-6">
                                <img src="{% static 'download.png' %}" class="card-imagea">
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-4" style="text-align: center; font-size: medium;">
                        <h2>EDUCATION</h2>
                            <br>
                            <p>SDN 04 Cilandak Barat</p>
                            <p>SMPN 85 Jakarta</p>
                            <p>SMAN 34 Jakarta</p>
                            <p>Universitas Indonesia</p>
                    </div>
                    <div class="col-sm-4" style="font-size: medium;">
                        <h2>PERSONAL DETAILS</h2>
                            <br>
                            <p><b>Date of Birth</b></p>
                            <p>11th June 2001</p>
                            <p><b>Address</b></p>
                            <p>Depok, Indonesia</p>
                            <p><b>NPM</b></p>
                            <p>1906398704</p>
                    </div>
            </div>
        </div>
	{% endblock %}

tugas/templates/Home.html
{% extends 'base.html' %}
{% load static %}
	{% block content %}
        <div class="card">
            <img src="{% static 'foto_home.jpg' %}" class="card-imageh">
            <p style="color: white; position: absolute; top: 50%; width: 100%; text-align: center; font-size: 60px;">Welcome to my personal website</p>
        </div>
	{% endblock %}

tugas/templates/More.html
{% extends 'base.html' %}
{% load static %}
	{% block content %}
        <div class="card">
            <div class="row">
                <div class="col-sm-8">
                    <h2><b>Pengalaman berorganisasi</b></h2>
                    <ul style="padding-left: 20px;">
                        <li>Wakil ketua Community of Love (COOL) remaja</li>
                            <p>(2019 - now)</p>
                        <li>Anggota tim pelayanan jemaat di bidang musik</li>
                            <p>(2017 - now)</p>
                        <li>Panitia COMPFEST di bidang Capture the Flag</li>
                            <p>(Februari 2020 - Oktober 2020)</p>
                        <li>Anggota tim silabus program Dasar-Dasar Pemrograman 0 (DDP0)</li>
                            <p>(Juli 2020 - September 2020)</p>
                        <li>Mentor program Dasar-Dasar Pemrograman 0 (DDP0)</li>
                            <p>(Agustus 2020 - September 2020)</p>
                        <li>Anggota kegiatan bakti sosial yang diadakan oleh FASILKOM UI angkatan 2019</li>
                            <p>(Desember 2019)</p>
                        <li>Anggota tim paduan suara SMA Grazia Vocalista</li>
                            <p>(Agustus 2016 - April 2019)</p>
                    </ul>
                    <br>
                </div>
                <div class="col-sm-4">
                    <img class="card-imagem"src="{% static 'baksos.jpg' %}" style="transform: rotate(8deg);">
                </div>
            </div>
            <div class="row">
                <div class="col-sm-8">
                    <h2 style="text-align: left; padding-left: 20px;"><b>Contact me</b></h2>
                    <div class="col-sm-1">
                        <a href="https://www.instagram.com/gerrad_nd/">
                            <img class="card-imagem1" src="{% static 'instagram.jpg' %}">                            
                        </a>
                        </div>
                    <div class="col-sm-1">
                        <a href="https://www.facebook.com/gerrad.natanael">
                            <img class="card-imagem1" src="{% static 'facebook.png' %}">
                        </a>
                    </div>
                    <div class="col-sm-1">
                        <a href="http://line.me/ti/p/~gerradnd">
                            <img class="card-imagem1" src="{% static 'line.png' %}">
                        </a>
                    </div>
                </div>
                <div class="col-sm-4">
                    <img class="card-imagem" src="{% static 'line_60271748161744.jpg' %}" style="transform: rotate(-8deg);">
                </div>
            </div>
        </div>
	{% endblock %}

tugas/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
	<!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
        <!-- jQuery library -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <!-- Latest compiled JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
	<link rel="stylesheet" href="{% static 'style.css' %}">
</head>

<body>
	<header class="header">
        <nav class="navbar navbar-style">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'tugas:home' %}"><b>Home</b></a></li>
                <li><a href="{% url 'tugas:about' %}"><b>About</b></a></li>
                <li><a href="{% url 'tugas:more' %}"><b>More</b></a></li>
		<li><a href="{% url 'story1:story1' %}"><b>story 1</b></a></li>
		<li><a href="{% url 'story5:jadwal' %}"><b>Jadwal</b></a></li>
            </ul>
        </nav>
        </header>
	{% block content %}


	{% endblock %}
</body>
</html>